CREATE TABLE IF NOT EXISTS TBL_JOB_APPLICANT
(
PAN_CARD VARCHAR(100) PRIMARY KEY,
JOB_ID VARCHAR(10) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
RESUME_PATH VARCHAR(256) NOT NULL,
STATUS ENUM ('SUBMITTED','SHORTLISTED','REJECTED')
);