ALTER TABLE TBL_SKILL_SET ADD COLUMN CREATED_BY VARCHAR(100);
ALTER TABLE TBL_SKILL_SET ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE TBL_SKILL_SET ADD COLUMN MODIFIED_AT TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;