CREATE TABLE IF NOT EXISTS TBL_JOB_DETAILS
(
ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(256) UNIQUE NOT NULL,
DESCRIPTION TEXT,
TEAM VARCHAR(100) NOT NULL,
MANAGER_EMAIL VARCHAR(100) NOT NULL,
NUM_OF_POSITIONS INT DEFAULT 1,
EXP_DT TIMESTAMP,
MIN_EXP INT NOT NULL,
MAX_EXP INT NOT NULL,
RESOURCE_ID VARCHAR(100) NOT NULL,
CREATED_BY VARCHAR(100) NOT NULL,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFIED_BY VARCHAR(100) NOT NULL,
MODIFIED_AT TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);