CREATE TABLE IF NOT EXISTS TBL_USER_INFO
(
EMAIL_ID VARCHAR(256) PRIMARY KEY,
USER_TYPE ENUM ('CANDIDATE', 'INTERVIEWER') DEFAULT 'INTERVIEWER',
MOCK_USER TINYINT,
LOGIN_PROVIDER ENUM ('DATABASE','GITHUB','MOCK') DEFAULT 'MOCK'
);