CREATE TABLE IF NOT EXISTS TBL_USER_INFO
(
ID INT PRIMARY KEY AUTO_INCREMENT,
EMAIL_ID VARCHAR(256) NOT NULL,
USER_TYPE VARCHAR(256) NOT NULL,
MOCK_USER TINYINT,
LOGIN_PROVIDER VARCHAR(256) NOT NULL
);