CREATE TABLE IF NOT EXISTS TBL_INTERVIEW_DETAILS
(
ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(256) NOT NULL,
JOB_DETAILS_ID INT,
CANDIDATE_EMAIL VARCHAR(256) NOT NULL,
INTERVIEW_STATUS ENUM ('SCHEDULED','CANCELLED','POSITIVE','NEGATIVE','OFFERED')
);