CREATE TABLE IF NOT EXISTS TBL_INTERVIEW_ROUND
(
ID INT PRIMARY KEY AUTO_INCREMENT,
INTERVIEW_ID INT NOT NULL,
CANDIDATE_EMAIL_ID VARCHAR(256) NOT NULL,
INTERVIEW_EMAIL_ID VARCHAR(256) NOT NULL,
TITLE VARCHAR(256) NOT NULL,
INTERVIEW_DATE VARCHAR(256) NOT NULL,
INTERVIEW_TIME VARCHAR(256) NOT NULL,
VIRTUAL_LINK VARCHAR(256) NOT NULL,
INTERVIEW_FEEDBACK VARCHAR(256),
INTERVIEW_STATUS ENUM ('SCHEDULED','CANCELLED','POSITIVE','NEGATIVE','OFFERED')
)